jdbc:
  driverClassName: ${JDBC_DRIVER_CLASS_NAME:org.postgresql.Driver}
  url: ${JDBC_URL:jdbc:postgresql://localhost:5432/test}
  username: ${JDBC_USER_NAME:postgres}
  password: ${JDBC_PASSWORD:postgres}